# Site
repository: dadfkim/dadfkim.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 김 영수
title: Senior Software Developer
email: dadfkim@hanmail.net
website: www.linkedin.com/in/kyskaritaslife

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  dadfkim
# stackoverflow_username: "00000001"
# dribbble_username: 
facebook_username: KYSKaritasLife
# flickr_username: 
# instagram_username: jameswgrant
linkedin_username: kyskaritaslife
# xing_username: 
# pinterest_username: 
# youtube_username: 
# googleplus_username: +dadfkim
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: 프로그램이력 및 개인성향
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
      - 프로그램이력 |
      13년 정도 일을 하고 있다. |
      자바 프로그램 언어가 주 사용언어 이고, php, solidity, go를 사용했다. |
      서버사이드 및 백엔드를 주로 개발했고,
      초창기에는 SI 프로젝트를 통해 프론트엔드개발을 하기도 했었다. (jquery 초창기까지)
      |
      - reditus 스타트업에서 |
      solidity 으로 이더리움 기반 erc20  및 erc721 을 개발, 삼성암호화폐 지갑내 등록 했다. |
      블록체인 스타트업회사에서 
      azure 클라우드 서비스를 사용, goeth 를 통해 테스트넷 메인넷 구축 했고,
      암호화페지갑을 메타마스크 커스터마이징을 통해 크롬 확장프로그램으로 등록 했었다. |
      - 한전 스마트배전연구소에서 |
      pure java 으로 외부 확장 프로그램을 정적 및 동적 수행 할 수 있는 제어 관리 프로그램을
      설계 및 개발 완료 했다. |
      - LMS 서비스 업체인 티처빌에서는 |
      jmetter, jconsole, jvisualvm 으로 jvm 및 resin 서버의 커스터 마이징 튜닝을 했었다. |
      메인페이지 상품에 대한 메모리로드 방식을 pure java 으로 구현 했었다. |
      메인 페이지 로딩 시간을2초 대에서 0.5초대로 로딩시간을 대폭 줄였었다. |
      - 국민카드 기간계 자산관리팀에서 기존 mystar 자산관리 시스템을 
      공통 및 대외계 연계(MCI, EAI) 그리고 스프링기반 kb프레임웍 교체로 고도화 완료 하였다. |
      - 아이케이커머스에서는
      php, ci 기반으로 이탈리아 명품 부틱 연동 및 국내 이커머스 업체 api 연동 및 개선을 진행 하였고,
      gsshop, lotteimall, ssg 부분 재고 연동부 재개발로 인해 품절율을 25%에서 5% 대로 낮추었다. |
      이탈리아 부틱의 상품 비정형 상품 데이터를 db 화 시켜 관리 할 수 있도록 처리, 
      기존 잘 못된 정보로 인해 상품등록 문제를 겪는 부분을 제외 할 수 있도록 필터처리 및 
      MD 가 실제 확인 하고 등록 할 수 있는 기반을 만들었다. |
      |
      그외 다양한 SI 프로젝트를 진행 하였다. |
      개인적으로는 서버사이드, 백엔드, 블록체인 및 인프라에 대한 관심이 많으며,
      기존 사회의 시스템에 대해 개선,
      그 부분에 기여하고 만들어갈 기회를 스타트업에서 찾고 있다. |
      | 
      프로그램 이력에 대한 세부적인 내용은 [링크드인](https://www.linkedin.com/in/kyskaritaslife)에서 확인 할 수 있다. |
      | 
      - 개인성향 |
      다른사람보다는 좀 더 빠르게 판단하고 이해 할 수 있다. |
      다만, 이해 하기까지 시간이 좀 더 걸리기도 한다. |
      그 이후에는 학습 된 부분에서는 다른 사람 보다 좀 더 큰
      시야와 역량을 발휘한다. |
      내 것이 아니라면, 도덕적인 책임감이 강하고,
      실제 회사 일 매출금액을 현금으로 800만원 이상 가지고 있어도, 횡령을 한 적이 없다. |
      무엇인가 나누기를 바라며, 
      개인적인 프로젝트를 통하거나 특기를 통해 많은 나눔 행사를 하기도 하고,
      개인 시간을 나눠 봉사활동을 많이 했다. |
      무엇인가 누군가를 통해 배우거나 얻게되면, 그로인해 나또한 배풀고 나누어야 한다는 것을
      옮다 라고 생각한다. |
      세계를 다니며 다양한 삶을 바라보고 왔으며,
      국내가 아닌 국외에서 일 할 기회를 준다면, 일할 마음이 있다. |
      세계로 여정은 파울로코엘료의 연금술사와 월터미디의 시크릿라이브 영화의 영향을 
      일부 받았다. |
      여러경험을 언젠가는 나만의 공간을 꾸며서, 경험의 이야기와 |
      경험자들의 쉼터를 제공 하는 것도 남은 생의 작은 소망이다. |

content:
  # - title: Projects # Title for the section
  #  layout: list # Type of content section (list/text)
  #  content:
  #    - layout: top-middle
  #      title: Super awesome project
  #      link: github.com/sproogen
        # link_text: Project Website
  #      additional_links:
  #        - title:  sproogen/modern-resume-theme
  #          icon: fab fa-github
  #          url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #      quote: >
  #        This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #      description: | # this will include new lines to allow paragraphs
  #        I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  # - title: Experience # Title for the section
  #  layout: list # Type of content section (list/text)
  #  content:
  #    - layout: left
  #      title: The Boring Company
  #      link: boringcompany.com
        # link_text: boringcompany.com
  #      sub_title: Senior Network System Administrator
  #      caption: November 2017 - Present
  #      quote: >
  #        Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
  #      description: | # this will include new lines to allow paragraphs
  #          Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  # - title: Education # Title for the section
  #  layout: list # Type of content section (list/text)
  #  content:
  #    - layout: left
  #      title: Harvard University
  #      caption: 2010 - 2013
  #      sub_title: BSc Computer Science
  #      quote: >
  #        Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
  #      description: | # this will include new lines to allow paragraphs
  #        During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

  #        I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.
  
  - title: 개인 업적 # Title for the section
    layout: list # Type of content section (list/text)
    content: | # this will include new lines to allow paragraphs
  #    Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #    - Rock climbing
  #    - Gaming
  #    - Knitting
  #    - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

  #    Look at this cool image  
  #    ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")
      2018년 을 끝으로 약 10년 동안 내가 바라던 버킷리스트를 마무리 했다.
      군대 전역이후 고은돌 봉사사활동을 시작으로 노숙인식사 나눔인 행심등에서 노력봉사를 했었고,
      2014년 커피를 시작으로, 
      커피삼남 강연, acts29cafe 브라질문화페스타, 커피&티페어 일일 바리스타 나눔,
      오픈팩토리 합류, 오픈팩토리 커피 특강,
      홍대 오르다 살롱, 세발자전거, 케이디, dmc 커피나눔등 커피 나눔을 
      통해 개인의 발전과 살믜 다양성을 이야기 하고 커피를 자비로 나눔 했었다.
      페이스북 나눔 프로젝트,  개인파티 영수의 홀딱쇼,를 통해 베품을 받은 것들을 다시 베풀었었다.

      - 2013 서울축제 봉사 및 축제 서포터즈 활동, 2014서울 시민춤단 100인의 춤단 
      - 살사 에버라틴 54기 수료
      - 네팔 마르디히말 트레킹 완주
      - 3차례 전국일주 (독도,울릉도),
      - 1000킬로의 여정 까미노 데 산티아고, 묵시아, 피스테라 프랑스 남부 일부(아를:빈센트반고흐)
      - 세계여행 1차 시도 (중국, 시베리아횡단열차, 만리장성, 백두산, 바이칼호수, 크램린궁, 붉은광장) 

      - 800일간의 세계여행 2차 시도 및 완료(베트남,캄보디아,태국,인도,네팔,독일,헝가리,그리스,이탈리아,바티칸,그린란드,아이슬란드,노르웨이,덴마크,영국,스웨덴,세르비아,불가리아,터키,요르단,이집트등 20개국 방문 - 총 231일 정도 소요)
      - 불교 4대 성지방문(룸비니,부다가야,사르나트,쿠시나가르)
      - 김해김씨 본 - 허황후 탄생지인 아요디아 지역 방문
      - 기독교 성지방문(성모마리아하우스, 메테오라, )
      - 세계불가사의 방문(피라미드,페트라,스톤헨지,앙코르와트) 외 유적지 및 박물관 방문
      - 네팔 히말라야 안나푸르나 베이스캠프를 단독등정에 성공했다. (15킬로배낭과함께)
      - 그리스 올림포스산 등반
      - 이집트 다합 - 스킨스쿠버 오픈워터 라이센스 취득 
      - 현재는 국궁(황학정 신사)

      - 그외
      세바시 열린번역 프로젝트
      돈키우스 특강, 코인트리(희망꽃학교) 기부
      책벌래 동양철학, 고은돌 봉사 활동, 경희사이버 총학생회 복지부국장
      수수보리아카데이, 전통주, 맥주과정 수료
      18년 멘사테스트 합격, EMAG 2018 belgrade, 영국 멘사 본부 방문 등을 했었다.

      - 링크
      [프로젝트나눔](https://www.facebook.com/groups/present2nanum) 비공개
      [춤단 어쩌다보니쇼케이스 용두동](https://youtu.be/izvUmzy93wY)
      [춤단 어쩌다보니쇼케이스 시민청 활짝라운지](https://youtu.be/7z-a5-dDPpI)
      [춤단 기사])(https://www.facebook.com/photo?fbid=10203840167741876&set=t.1150686063)
      [영수 홀딱쇼](https://www.facebook.com/events/1510125522602380) 비공개

      [불교 성지 1](https://www.facebook.com/photo.php?fbid=10215025298403152&set=t.1150686063&type=3)
      [불교 성지 2](https://www.facebook.com/photo.php?fbid=10214982730138972&set=t.1150686063&type=3)

      - 세계불가사의
      [페트라](https://www.facebook.com/photo.php?fbid=10216445182659371&set=t.1150686063&type=3)
      [피라미드](https://www.facebook.com/photo.php?fbid=10216589768953938&set=t.1150686063&type=3)
      [앙코르와트](https://www.facebook.com/photo.php?fbid=10214849057117230&set=t.1150686063&type=3)
      [스톤헨지](https://www.facebook.com/photo?fbid=10215962798480068&set=a.1639350900903)

      [올림포스산]((https://www.facebook.com/photo.php?fbid=10215593977579776&set=t.1150686063&type=3)

      -커피
      [케이디 커피 나눔 1](https://www.facebook.com/photo?fbid=10204495338800743&set=a.1639350900903)
      [케이디 커피 나눔 2](https://www.facebook.com/photo?fbid=10203985149246323&set=a.1639350900903)

      [브라질문화페스타 1](https://www.facebook.com/acts29cafe/photos/t.1150686063/552972478140283)
      [브라질문화페스타 2](https://www.facebook.com/photo.php?fbid=10203639887174987&set=t.1150686063&type=3)
      [브라질문화페스타 3](https://www.facebook.com/acts29cafe/photos/t.1150686063/552971918140339/?type=3)
      [행화탕 커피 행사](https://www.facebook.com/photo?fbid=10210096778673239&set=a.1639350900903)

      - 강연
      [세남자 이야기](https://www.facebook.com/groups/692403150806856)
      [러빙핸즈 초록리본도서관](https://www.facebook.com/acts29cafe/photos/t.1150686063/621445734626290/?type=3)
      [러빙핸즈 초록리본도서관](https://www.facebook.com/acts29cafe/photos/t.1150686063/635234506580746/?type=3)

      [영등포 하자센터 첫번쨰 1](https://www.facebook.com/acts29cafe/photos/t.1150686063/546061895498008/?type=3)
      [영등포 하자센터 첫번쨰 2](https://www.facebook.com/acts29cafe/photos/t.1150686063/546063472164517/?type=3)

      [영등포 하자센터 두번째 1](https://www.facebook.com/acts29cafe/photos/t.1150686063/591695034268027/?type=3)
      [영등포 하자센터 두번째 2](https://www.facebook.com/acts29cafe/photos/t.1150686063/591694137601450)
      [영등포 하자센터 두번째 3](https://www.facebook.com/photo?fbid=795210357197072&set=t.1150686063)

      [세바시 열린번역](https://www.facebook.com/photo.php?fbid=726099004096217&set=t.1150686063&type=3
      [세바시 열린번역](https://www.facebook.com/sebasi15/photos/t.1150686063/749063955116392)

      [마르디히말](https://www.facebook.com/we.playplanet/photos/t.1150686063/658438997585992)
      [히말라야 안나푸르나 베이스캠프 1](https://www.facebook.com/photo.php?fbid=10215127791005403&set=t.1150686063&type=3)
      [히말라야 안나푸르나 베이스캠프 2](https://www.facebook.com/photo.php?fbid=10215127637481565&set=t.1150686063&type=3)
      [오픈워터라이센스](https://www.facebook.com/photo.php?fbid=10216554563233817&set=t.1150686063&type=3)
      [세계여행 기록들](https://www.facebook.com/KYSKaritasLife/photos_albums)
      [개인 생각정리](https://www.facebook.com/media/set/?set=a.10215797801515247&type=3)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
